ScanerApi/Areas/Web/Controllers/LogController.cs
using Business.Manager;
using Business.QueryModels.Data1c;
using Business.QueryModels.Good;
using Business.QueryModels.Logs;
using Business.QueryModels.Task;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScanerApi.Areas.Web.Controllers
{
    public class LogController : Controller
    {
        private readonly TaskManager _taskManager;
        private readonly GoodManager _goodManager;
        private readonly LogManager _logManager;

        public LogController(TaskManager taskManager, GoodManager goodManager, LogManager logManager)
        {
            _taskManager = taskManager;
            _goodManager = goodManager;
            _logManager = logManager;
        }

        // GET: Web/Log
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Search(string planNum)
        {
            var task = _taskManager.GetTaskById(new TaskQueryModel { PlanNum = planNum });
            var logs = _logManager.LogsByTask(new LogsListQueryModel { TaskId = task.Id });
            ViewBag.Task = task;
            return PartialView("Search", logs);
        }

        public ActionResult ScanerGoods(int taskId)
        {
            var data = _goodManager.GetGoods(new GoodQueryModel { TaskId = taskId });
            return View("ScanerGoods", data);
        }

        public ActionResult DocData(string planNum)
        {
            var data = _taskManager.DocDataModels(new Data1cQueryModel { PlanNum = planNum });
            return View("DocData", data);
        }
    }
}

ScanerApi/Areas/Web/Controllers/PdfController.cs
using Business.Manager;
using Business.Models;
using Business.QueryModels.Data1c;
using Business.QueryModels.Good;
using Business.QueryModels.Task;
using PdfSharp;
using PdfSharp.Pdf;
using ScanerApi.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using TheArtOfDev.HtmlRenderer.PdfSharp;

namespace ScanerApi.Areas.Web.Controllers
{
    public class PdfController : Controller
    {
        private readonly TaskManager _taskManager;
        private readonly GoodManager _goodManager;

        public PdfController(TaskManager taskManager, GoodManager goodManager)
        {
            _taskManager = taskManager;
            _goodManager = goodManager;
        }

        public ActionResult Disqus()
        {
            return View();
        }
        public string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext,
                                                                         viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View,
                                             ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }

        public FileResult Index(string PlanNum)
        {
            var task = _taskManager.GetTaskById(new TaskQueryModel { PlanNum = PlanNum });
            var goods = _goodManager.GetGoods(new GoodQueryModel { TaskId = task.Id });
            var differences = _taskManager.Differences(new TaskQueryModel { TaskId = task.Id, PlanNum = task.PlanNum });
            var test = differences.receipts.ToString();
            var report = new PdfViewModels { task = task, goods = goods, differences = differences };
            MemoryStream stream = new MemoryStream();           
            string content = RenderRazorViewToString("Index", report);

            PdfDocument pdf = PdfGenerator.GeneratePdf(content, PageSize.A4);
            pdf.Save(stream, false);

            //return Json(new { success = true, data = content }, JsonRequestBehavior.AllowGet);
            return File(stream.ToArray(), "application/pdf");
        }

        public ActionResult Goods(GoodQueryModel model)
        {
            var data = _goodManager.GetGoodWithBarcode(model);
            return View("Goods", data);
        }

        /// <summary>
        /// Факт
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult ScanerGoods(GoodQueryModel model)
        {
            var task = _taskManager.GetTaskById(new TaskQueryModel { PlanNum = model.PlanNum });
            model.TaskId = task.Id;
            var data = _goodManager.GetGoods(model);
            return View("ScanerGoods", data);
        }

        /// <summary>
        /// План
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult DocData(Data1cQueryModel model)
        {
            var data = _taskManager.DocDataModels(model);
            return View("DocData", data);
        }

    }
}

ScanerApi/Areas/Web/Views/Log/DocData.cshtml
@model IEnumerable<Business.Models.Scaner_1cDocDataModel>
@{ ViewBag.Title = "План";}
<table class="table" style="table-layout:fixed;">
    <tr>
        <th>
            Номер планирование
        </th>
        <th>
            РОТ
        </th>
        <th>
            Артикуль
        </th>
        <th>
            ШК
        </th>
        <th>
            Количество
        </th>
        <th>
            Дата документа в 1С
        </th>
        <th>
            Дата создание
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.PlanNum)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.NumberDoc)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.Article)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.Barcode)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.DateDoc)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
        </tr>
    }

</table>

ScanerApi/Areas/Web/Views/Log/Index.cshtml
@{
    ViewBag.Title = "Логи";
    Layout = "~/Areas/Web/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        @using (Ajax.BeginForm("Search", new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "GET",
            UpdateTargetId = "result",
            //LoadingElementId = "loader",
            //OnBegin = "onAjaxBegin",
            //OnComplete = "onAjaxComplete"
        }))
        {
            <div class="row g-3 align-items-center">
                <div class="col-auto">
                    <input type="text" class="form-control" id="planNum" name="planNum" placeholder="Номер планирование">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary">Поиск</button>
                </div>
            </div>
        }
    </div>
    <div class="col-md-12" id="result"></div>
</div>

ScanerApi/Areas/Web/Views/Log/ScanerGoods.cshtml
@model IEnumerable<Business.Models.GoodsModel>
@{ ViewBag.Title = "Факт";}
<table class="table" style="table-layout:fixed;">
    <tr>
        <th>
            Артикуль
        </th>
        <th>
            Название
        </th>
        <th>
            Количество
        </th>
        <th>
            ШК
        </th>
        <th>
            Короб
        </th>
        <th>
            Время
        </th>
    </tr>

    @foreach (var item in Model)
    {
        var box = item.BoxId == null || item.BoxId == 0 ?
            "" : Model.FirstOrDefault(m => m.Id == item.BoxId).BarCode;
        <tr>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.GoodArticle)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.GoodName)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.CountQty)
            </td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.BarCode)
            </td>
            <td style="padding-left:10px; padding-right:10px;">@box</td>
            <td style="padding-left:10px; padding-right:10px;">
                @Html.DisplayFor(modelItem => item.Created)
            </td>
        </tr>
    }

</table>

ScanerApi/Areas/Web/Views/Log/Search.cshtml
@model IEnumerable<Business.Models.LogsModel>
@{
    var task = (Business.Models.TasksModel)ViewBag.Task;
    //Model.Any() ? Model.FirstOrDefault(m => !string.IsNullOrEmpty(m.Request)).Request : "";
}

<div class="row">
        @if (task != null && !string.IsNullOrEmpty(task.PlanNum))
        {
            <div class="col-md-12 m-2">
                <a class="btn btn-info" style="padding-right:10px;" href="@Url.Action("Index","Pdf",new { PlanNum = task.PlanNum })" target="_blank">Акт</a>
                <a class="btn btn-danger" style="padding-right: 10px; " href="@Url.Action("ScanerGoods",new { taskId = task.Id })" target="_blank">Отсканированные товары</a>
                <a class="btn btn-primary" style="padding-right:10px;" href="@Url.Action("DocData",new { planNum = task.PlanNum })" target="_blank">Данные с 1с</a>
            </div>
        }
        <div class="col-md-12">
            <table class="table"  width="100%"  style="table-layout:fixed;">
                <tr>
                    <th width="10%">
                        Номер планирование
                    </th>
                    <th width="15%">
                        Название процесса
                    </th>
                    <th width="25%" >
                        Комментарий
                    </th>
                    <th width="10%" style="padding-left:10px;padding-right:10px;">
                        Время
                    </th>
                    <th  style="padding-left:10px;padding-right:10px;">

                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td >
                            @task.PlanNum
                        </td>
                        <td nowrap style="padding-left:10px;padding-right:10px;">
                            @Html.DisplayFor(modelItem => item.ProcessName)
                        </td>
                        <td width="25%" style="padding-left:10px;padding-right:5px;">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td nowrap style="padding-left:10px;padding-right:10px;">
                            @Html.DisplayFor(modelItem => item.Created)
                        </td>

                    </tr>
                }
            </table>
        </div>
    </div>