ScanerApi/Areas/Web/Controllers/LogController.cs
using Business.Manager;
using Business.QueryModels.Data1c;
using Business.QueryModels.Good;
using Business.QueryModels.Logs;
using Business.QueryModels.Task;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScanerApi.Areas.Web.Controllers
{
    public class LogController : Controller
    {
        private readonly TaskManager _taskManager;
        private readonly GoodManager _goodManager;
        private readonly LogManager _logManager;

        public LogController(TaskManager taskManager, GoodManager goodManager, LogManager logManager)
        {
            _taskManager = taskManager;
            _goodManager = goodManager;
            _logManager = logManager;
        }

        // GET: Web/Log
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Search(string planNum)
        {
            var task = _taskManager.GetTaskById(new TaskQueryModel { PlanNum = planNum });
            var logs = _logManager.LogsByTask(new LogsListQueryModel { TaskId = task.Id });
            ViewBag.Task = task;
            return PartialView("Search", logs);
        }

        public ActionResult ScanerGoods(int taskId)
        {
            var data = _goodManager.GetGoods(new GoodQueryModel { TaskId = taskId });
            return View("ScanerGoods", data);
        }

        public ActionResult DocData(string planNum)
        {
            var data = _taskManager.DocDataModels(new Data1cQueryModel { PlanNum = planNum });
            return View("DocData", data);
        }
    }
}

ScanerApi/Areas/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    
    @*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
    <link href="~/Areas/Web/Contents/css/site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Scaner", "Index", "Log", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <div class="loading-modal" style="z-index:99999;"></div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Areas/Web/Contents/js/site.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>